plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/himelbarman/Documents/Assignment-5/B14-A05-DevStack-main/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]